version: '3'
services:
  zookeeper:
    image: zookeeper:3.6
    container_name: zookeeper-kafka
    ports:
      - "12181:2181"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes

  kafka-1:
    image: bitnami/kafka:2.5.0
    container_name: kafka-1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.81.86.129:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092      # 配置kafka的监听端口

  kafka-2:
    image: bitnami/kafka:2.5.0
    container_name: kafka-2
    ports:
      - "9093:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.81.86.129:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092

  kafka-3:
    image: bitnami/kafka:2.5.0
    container_name: kafka-3
    ports:
      - "9094:9092"
    environment:
      # 负责发布外网地址，这个地址会发布到zookeeper中
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.81.86.129:9094
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 3
      ALLOW_PLAINTEXT_LISTENER: yes
      # 负责绑定网卡
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092

  # kafka web 管理工具 用户名密码：admin/admin
  kafka-map:
    container_name: kafka-map
    image: dushixiang/kafka-map:latest
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "9095:8080"
