version: '3'
services:
  etcd1:
    container_name: etcd1
    image: quay.io/coreos/etcd:v3.5.0
    command: etcd --name etcd1 --initial-advertise-peer-urls http://etcd1:2380 --listen-peer-urls http://0.0.0.0:2380 --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://etcd1:2379 --initial-cluster-token etcd-cluster --initial-cluster etcd1=http://etcd1:2380,etcd2=http://etcd2:2382,etcd3=http://etcd3:2384 --initial-cluster-state new
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - etcd-network

  etcd2:
    container_name: etcd2
    image: quay.io/coreos/etcd:v3.5.0
    command: etcd --name etcd2 --initial-advertise-peer-urls http://etcd2:2382 --listen-peer-urls http://0.0.0.0:2382 --listen-client-urls http://0.0.0.0:2381 --advertise-client-urls http://etcd2:2381 --initial-cluster-token etcd-cluster --initial-cluster etcd1=http://etcd1:2380,etcd2=http://etcd2:2382,etcd3=http://etcd3:2384 --initial-cluster-state new
    ports:
      - 2381:2379
      - 2382:2380
    networks:
      - etcd-network

  etcd3:
    container_name: etcd3
    image: quay.io/coreos/etcd:v3.5.0
    command: etcd --name etcd3 --initial-advertise-peer-urls http://etcd3:2384 --listen-peer-urls http://0.0.0.0:2384 --listen-client-urls http://0.0.0.0:2383 --advertise-client-urls http://etcd3:2383 --initial-cluster-token etcd-cluster --initial-cluster etcd1=http://etcd1:2380,etcd2=http://etcd2:2382,etcd3=http://etcd3:2384 --initial-cluster-state new
    ports:
      - 2383:2379
      - 2384:2380
    networks:
      - etcd-network

networks:
  etcd-network: