version: '3'
services:
  pinpoint-collector:
    image: pinpointdocker/pinpoint-collector:latest
    container_name: pinpoint-collector
    ports:
      - "9991:9991"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASS=dongyang106
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    depends_on:
      - db

  pinpoint-web:
    image: pinpointdocker/pinpoint-web:latest
    container_name: pinpoint-web
    ports:
      - "8080:8080"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASS=dongyang106
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - COLLECTOR_IP=pinpoint-collector
    depends_on:
      - db
      - pinpoint-collector

  db:
    image: mysql:latest
    container_name: pinpoint-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=dongyang106
